language: java
jdk:
  - openjdk8

sudo: required
services:
  - docker

jobs:
  include:

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./gradlew release --scan --no-daemon -i
        on:
          tags: true
          branch: master
